apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-repo
  namespace: default
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: repository
    repo: catalog-distros-sandbox
    revision: v2.0.0
  downstream:
    package: example-repo
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
    - image: gcr.io/kpt-fn/set-namespace:v0.4.1
      configMap:
        namespace: example # kpt-set: ${clusterName}
