apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: example
  namespace: default
spec:
  # Since injection only injects the spec, we need the name here as
  # well as in metadata.
  clusterName: example
  cnis:
  - macvlan
  - ipvlan
  - sriov
  masterInterface: eth1
